version: '3.6'
services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    environment:
      - VIRTUAL_HOST=nexus.backendteam.xyz
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=nexus.backendteam.xyz
      - LETSENCRYPT_EMAIL=email@nexus.backendteam.xyz
    volumes:
      - ./nexus-data:/nexus-data
    ports:
      - "8081:8081"
    networks:
      - nginx-proxy-network
networks:
  nginx-proxy-network:
    external: true