version: '3.6'
services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    environment:
      - VIRTUAL_HOST=nexus.projectmoonwalk.io
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=nexus.projectmoonwalk.io
      - LETSENCRYPT_EMAIL=email@nexus.projectmoonwalk.io
    volumes:
      - ./nexus-data:/nexus-data
    ports:
      - "8081:8081"
    networks:
      - nginx-proxy-network
volumes:
  nexus-data:
networks:
  nginx-proxy-network:
    external: true