version: '3.6'
services:
#  nginx:
#    image: nginx:latest
#    container_name: nginx-nexus
#    environment:
#      - VIRTUAL_HOST=nexus.backendteam.xyz
#      - LETSENCRYPT_HOST=nexus.backendteam.xyz
#      - LETSENCRYPT_EMAIL=email@nexus.backendteam.xyz
#    volumes:
#      - ./logs/nginx:/var/log/nginx
#      - ./nginx/nexus.conf:/etc/nginx/conf.d/default.conf
#    restart: always
#    networks:
#      - nginx-proxy-network
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    environment:
      - VIRTUAL_HOST=nexus.backendteam.xyz
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=nexus.backendteam.xyz
      - LETSENCRYPT_EMAIL=email@nexus.backendteam.xyz
    volumes:
      - ./nexus-data:/nexus-data
    ports:
      - "8081:8081"
    networks:
      - nginx-proxy-network
networks:
  nginx-proxy-network:
    external: true