version: '2'
services:
  jenkins:
    image: 'docker.io/bitnami/jenkins:2-debian-10'
    ports:
      - '80:8082'
     # - '443:8443'
      - '50000:50000'
    volumes:
      - 'jenkins_data:/bitnami/jenkins'
    environment:
      - VIRTUAL_HOST=jenkins.backendteam.xyz
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=jenkins.backendteam.xyz
      - LETSENCRYPT_EMAIL=email@jenkins.backendteam.xyz
      #- JENKINS_USERNAME=admin
      #- JENKINS_PASSWORD=1
    networks:
      - nginx-proxy-network
volumes:
  jenkins_data:
    driver: local

networks:
  nginx-proxy-network:
    external: true