version: "3.3"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1qaz2wsxddd!
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress1@!
    networks:
     - nginx-proxy-network
    
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8001:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress1@!
      WORDPRESS_DB_NAME: wordpress
      VIRTUAL_HOST: portal.projectmoonwalk.io
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: portal.projectmoonwalk.io
      LETSENCRYPT_EMAIL: email@portal.projectmoonwalk.io
    networks:
     - nginx-proxy-network
      
volumes:
  db_data: {}
  wordpress_data: {}

networks:
  nginx-proxy-network:
    external: true
