version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      - MONITORING_TOKEN=8fc40e89-b465-4bbd-ad49-3849c879aca6
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS="Topic1:1:3,Topic2:1:1:compact"
      - MONITORING_TOKEN=8fc40e89-b465-4bbd-ad49-3849c879aca6
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
